FROM alpine
RUN apk add --no-cache bash

ADD https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.aarch64 /usr/bin/ttyd
RUN chmod +x /usr/bin/ttyd
ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-arm64 /sbin/tini
RUN chmod +x /sbin/tini

EXPOSE 7681
WORKDIR /root

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["ttyd", "bash"]